<?php if ( ! defined('IN_DiliCMS')) exit('No direct script access allowed');
$setting['category']['oa_power']=array (
  1 => 
  array (
    'classid' => '1',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '总经理',
    'desc' => '总经理拥有所有权限',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  2 => 
  array (
    'classid' => '2',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '财务',
    'desc' => '财务只负责钱数 对账',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  3 => 
  array (
    'classid' => '3',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '采购',
    'desc' => '采购负责相关采购信息入库。',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  4 => 
  array (
    'classid' => '4',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '保管',
    'desc' => '负责工厂部分用品库存核发核对',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  5 => 
  array (
    'classid' => '5',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '货源',
    'desc' => '负责货源部审核',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  6 => 
  array (
    'classid' => '6',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '生产',
    'desc' => '生产相关信息',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  7 => 
  array (
    'classid' => '7',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '发货',
    'desc' => '产品发货人员',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  8 => 
  array (
    'classid' => '8',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '司务',
    'desc' => '后勤',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  9 => 
  array (
    'classid' => '9',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '机修',
    'desc' => '机修部',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  10 => 
  array (
    'classid' => '10',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => '董事长',
    'desc' => '董事长',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
  11 => 
  array (
    'classid' => '11',
    'parentid' => '0',
    'level' => '1',
    'path' => '',
    'name' => 'root',
    'desc' => 'root',
    'act' => '',
    'children' => '0',
    'deep' => 0,
  ),
);