<?php if ( ! defined('IN_DiliCMS')) exit('No direct script access allowed');
$setting['models']['hyb_mingxibiao']=array (
  'id' => '4',
  'name' => 'hyb_mingxibiao',
  'description' => '[货源]日明细表',
  'perpage' => '30',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    26 => 
    array (
      'id' => '26',
      'name' => 'date',
      'description' => '日期',
      'model' => '4',
      'type' => 'datetime',
      'length' => '12',
      'values' => '',
      'width' => '100',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    27 => 
    array (
      'id' => '27',
      'name' => 'diqu',
      'description' => '[货源]地区分类id',
      'model' => '4',
      'type' => 'select_from_model',
      'length' => '10',
      'values' => 'hyb_diqu|name',
      'width' => '100',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    22 => 
    array (
      'id' => '22',
      'name' => 'yewuyuan3',
      'description' => '业务员3',
      'model' => '4',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '如果不存在多个业务员，则不填写',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    21 => 
    array (
      'id' => '21',
      'name' => 'yewuyuan2',
      'description' => '业务员2',
      'model' => '4',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '非必须填写，如果不存在多个业务员则不填',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    20 => 
    array (
      'id' => '20',
      'name' => 'yewuyuan1',
      'description' => '业务员1',
      'model' => '4',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '如果没有业务员则填写胴体或者自送胴体',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    23 => 
    array (
      'id' => '23',
      'name' => 'yewuyuan4',
      'description' => '业务员4',
      'model' => '4',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '如果不存在多个业务员则不填写',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    24 => 
    array (
      'id' => '24',
      'name' => 'yewuyuan5',
      'description' => '业务员5',
      'model' => '4',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    25 => 
    array (
      'id' => '25',
      'name' => 'qq_dongti_mingxi_id',
      'description' => '[前区]胴体明细id',
      'model' => '4',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '50',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '选择胴体明细id',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '26',
    1 => '27',
    2 => '22',
    3 => '21',
    4 => '20',
    5 => '23',
    6 => '24',
    7 => '25',
  ),
  'searchable' => 
  array (
    0 => '26',
    1 => '27',
    2 => '22',
    3 => '21',
    4 => '20',
    5 => '23',
    6 => '24',
    7 => '25',
  ),
);