<?php if ( ! defined('IN_DiliCMS')) exit('No direct script access allowed');
$setting['models']['news']=array (
  'id' => '1',
  'name' => 'news',
  'description' => '新闻中心',
  'perpage' => '20',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    8 => 
    array (
      'id' => '8',
      'name' => 'classid',
      'description' => '分类名称',
      'model' => '1',
      'type' => 'select_from_model',
      'length' => '10',
      'values' => 'news|name',
      'width' => '50',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    1 => 
    array (
      'id' => '1',
      'name' => 'title',
      'description' => '标题',
      'model' => '1',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '256',
      'height' => '22',
      'rules' => 'required',
      'ruledescription' => 'is  not null',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'stitle',
      'description' => '简短标题',
      'model' => '1',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '100',
      'height' => '20',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    3 => 
    array (
      'id' => '3',
      'name' => 'content',
      'description' => '内容',
      'model' => '1',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '300',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '1',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'scontent',
      'description' => '文章概要',
      'model' => '1',
      'type' => 'wysiwyg_basic',
      'length' => '0',
      'values' => '',
      'width' => '300',
      'height' => '100',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '1',
      'editable' => '1',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'author',
      'description' => '作者',
      'model' => '1',
      'type' => 'input',
      'length' => '120',
      'values' => '',
      'width' => '60',
      'height' => '20',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '2',
      'editable' => '0',
    ),
    6 => 
    array (
      'id' => '6',
      'name' => 'keywords',
      'description' => '关键词',
      'model' => '1',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '8',
    1 => '1',
    2 => '2',
  ),
  'searchable' => 
  array (
    0 => '1',
    1 => '3',
    2 => '4',
    3 => '5',
    4 => '6',
  ),
);