<?php if ( ! defined('IN_DiliCMS')) exit('No direct script access allowed');
$setting['models']['oa_users']=array (
  'id' => '2',
  'name' => 'oa_users',
  'description' => 'oa用户表',
  'perpage' => '25',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    9 => 
    array (
      'id' => '9',
      'name' => 'name',
      'description' => '用户名',
      'model' => '2',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '100',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '必填',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    10 => 
    array (
      'id' => '10',
      'name' => 'pass',
      'description' => 'oa用户密码',
      'model' => '2',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '100',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '密码必填',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    11 => 
    array (
      'id' => '11',
      'name' => 'email',
      'description' => '用户电子邮箱',
      'model' => '2',
      'type' => 'input',
      'length' => '256',
      'values' => '',
      'width' => '150',
      'height' => '30',
      'rules' => 'valid_email',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    12 => 
    array (
      'id' => '12',
      'name' => 'power',
      'description' => '部门',
      'model' => '2',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'oa_power|name',
      'width' => '50',
      'height' => '30',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '9',
    1 => '10',
    2 => '11',
    3 => '12',
  ),
  'searchable' => 
  array (
  ),
);