<?php if ( ! defined('IN_DiliCMS')) exit('No direct script access allowed');
$setting['models']['qq_dongti_rimingxi']=array (
  'id' => '3',
  'name' => 'qq_dongti_rimingxi',
  'description' => '[前区]胴体明细表',
  'perpage' => '30',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    13 => 
    array (
      'id' => '13',
      'name' => 'chehao',
      'description' => '车号',
      'model' => '3',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'name' => 'checi',
      'description' => '车次',
      'model' => '3',
      'type' => 'int',
      'length' => '4',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    15 => 
    array (
      'id' => '15',
      'name' => 'date',
      'description' => '日期',
      'model' => '3',
      'type' => 'datetime',
      'length' => '12',
      'values' => '',
      'width' => '100',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '0',
    ),
    16 => 
    array (
      'id' => '16',
      'name' => 'dongti',
      'description' => '胴体重',
      'model' => '3',
      'type' => 'float',
      'length' => '10',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    17 => 
    array (
      'id' => '17',
      'name' => 'dongtino',
      'description' => '胴体只数',
      'model' => '3',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    18 => 
    array (
      'id' => '18',
      'name' => 'canji',
      'description' => '残鸡重量',
      'model' => '3',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    19 => 
    array (
      'id' => '19',
      'name' => 'canjino',
      'description' => '残鸡只数',
      'model' => '3',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '60',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '13',
    1 => '14',
    2 => '15',
    3 => '16',
    4 => '17',
    5 => '18',
    6 => '19',
  ),
  'searchable' => 
  array (
    0 => '13',
    1 => '14',
    2 => '16',
    3 => '17',
    4 => '18',
    5 => '19',
  ),
);